### ISSUE TITLE
Tshwane group 6 & 7 not showing today (07/12) and tomorrow's schedules

### ISSUE THREAD

**Issue by jacosmitza** [beyarkay/eskom-calendar#187] opened 2022-12-07 07:14 UTC
Tshwane group 6 & 7 not showing today (07/12) and tomorrow's schedules.

![image](https://user-images.githubusercontent.com/4435207/206112322-3dc5951c-802e-4d51-b703-863df3d2f1aa.png)
![image](https://user-images.githubusercontent.com/4435207/206112533-109ce47a-50c2-41bf-8af2-fd06ca237f8a.png)

**Comment by beyarkay** [comment] 2022-12-07 08:36
Hey, thanks for opening the issue. I think this was caused because I only just managed to update the schedule to stage 4 (see https://github.com/beyarkay/eskom-calendar/pull/188). When #188 gets merged in about 20 minutes, you should see the new schedule in your calendar.

**Comment by beyarkay** [comment] 2022-12-07 08:44
I've confirmed that the issue was caused by the schedule not being up-to-date:

<img width="1100" alt="Screenshot 2022-12-07 at 10 43 56" src="https://user-images.githubusercontent.com/33420535/206130659-56a652e3-bd42-4106-84c6-9a3638343bbd.png">


Once [this build](https://github.com/beyarkay/eskom-calendar/actions/runs/3637214338/jobs/6137983402) is finished,  tshwane (and all other places) should be fixed.

**Comment by beyarkay** [comment] 2022-12-07 08:49
Okay @jacosmitza tshwane should be fixed now, although it'll take a few more minutes for all the remaining areas to be fixed. I'm closing this issue

**Closed by beyarkay** 2022-12-07 08:49 UTC
Labels: waiting-to-close

**Comment by beyarkay** [comment] 2022-12-07 08:57
I can confirm that tshwane has been updated:

```
╰→ curl -sL https://github.com/beyarkay/eskom-calendar/releases/download/latest/machine_friendly.csv | rg "tshwane-group-(6|7)"
gauteng-tshwane-group-7,2022-12-07T10:00:00+02:00,2022-12-07T12:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1600340502628356096"
gauteng-tshwane-group-7,2022-12-07T18:00:00+02:00,2022-12-07T20:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1600340502628356096"
gauteng-tshwane-group-7,2022-12-08T02:00:00+02:00,2022-12-08T04:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1600340502628356096"
gauteng-tshwane-group-7,2022-12-08T10:00:00+02:00,2022-12-08T12:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1600340502628356096"
gauteng-tshwane-group-7,2022-12-08T18:00:00+02:00,2022-12-08T20:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1600340502628356096"
gauteng-tshwane-group-7,2022-12-09T00:00:00+02:00,2022-12-09T02:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1600340502628356096"
gauteng-tshwane-group-7,2022-12-09T08:00:00+02:00,2022-12-09T10:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1600340502628356096"
gauteng-tshwane-group-7,2022-12-09T16:00:00+02:00,2022-12-09T18:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1600340502628356096"
gauteng-tshwane-group-7,2022-12-10T00:00:00+02:00,2022-12-10T02:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1600340502628356096"
gauteng-tshwane-group-7,2022-12-10T08:00:00+02:00,2022-12-10T10:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1600340502628356096"
gauteng-tshwane-group-7,2022-12-10T16:00:00+02:00,2022-12-10T18:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1600340502628356096"
gauteng-tshwane-group-7,2022-12-11T00:00:00+02:00,2022-12-11T02:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1600340502628356096"
gauteng-tshwane-group-7,2022-12-11T08:00:00+02:00,2022-12-11T10:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1600340502628356096"
...
```

It might take a bit of time for your calendar to pull the changes, but usually there's an "update" or "sync" button that will force your calendar app to check for and download any updates.

**Comment by jacosmitza** [comment] 2022-12-07 09:13
Thanks
