### ISSUE TITLE
Add Loadshedding for Stellenbosch/Raithby

### ISSUE THREAD

**Issue by ChristoViljoen** [beyarkay/eskom-calendar#74] opened 2022-09-22 19:57 UTC
Hey!

Would you be able to add the Raithby schedule as well. It falls under Stellenbosch. 

EskomSePush has it as Raithby(8) with description Eskom Direct, Stellenbosch, Western Cape. Raithby doesn't fall under Stellenbosch's main schedule. It seems to fall under the Stellenbosch Farmers block 8 which includes:

Block 8: Cloetesville, De Zalze, Franschhoek, Jamestown, Raithby, Koelenhof, Kylemore, Kayamandi, Vlottenburg, Plankenburg, La Motte, Lanquedoc (Dwarsrivier), Lynedoch and Pniel

This is the best problem solved sinced sliced cheese! Well done champ!

**Comment by beyarkay** [comment] 2022-09-23 08:30
Hey! Thanks for your feedback, I really appreciate it. This is a duplicate of #47 so I'm gonna close this one, but feel free to watch issue #47  to be notified of progress on this.

**Closed by beyarkay** 2022-09-23 08:30 UTC
