### ISSUE TITLE
Possible error in parsing observed for CPT region 7

### ISSUE THREAD

**Issue by PMStephanv** [beyarkay/eskom-calendar#54] opened 2022-09-17 13:50 UTC
Hi Boyd
Thank you for your app.  Imported into Google Calander.

Seems to be a "duplication" error for some stage 5, CPT region 7.  
Today the power was off 12:00-14:00 (first pic)
Second "duplication" tomorrow as exaple

![BoydLoadsheedin CapeTown region 7 2022-09-17 10-1230 incorrect](https://user-images.githubusercontent.com/113780990/190860286-62d19de7-7e63-400b-9e41-a4e691fea119.png)
![BoydLoadsheding CapeTown region 7 2022-09-17 1800-2030 and again 2000-2230](https://user-images.githubusercontent.com/113780990/190860284-b77de8a5-502c-4707-b5a6-cd44d5bfa4b2.png)

**Comment by beyarkay** [comment] 2022-09-17 14:36
Will check this out tomorrow, but might be a duplicate of https://github.com/beyarkay/eskom-calendar/issues/53

**Comment by beyarkay** [comment] 2022-09-18 19:40
Hi @PMStephanv thanks for raising the issue. I'm gonna close this one as it is indeed a duplicate of #53, but don't worry, I'll send progress updates on issue #53 so you can follow that issue if you want to keep track of when this bug will be fixed.

**Closed by beyarkay** 2022-09-18 19:40 UTC
Labels: waiting-on-maintainer
