### ISSUE TITLE
Not updating on Tshwane 13?

### ISSUE THREAD

**Issue by Iksplisit** [beyarkay/eskom-calendar#230] opened 2023-01-08 13:55 UTC
I checked my calendars and re added the link, but still no info after today, is there an issue or did I miss something?

**Comment by beyarkay** [comment] 2023-01-08 16:07
Hey, I think this is an issue with the latest PR [not being merged](https://github.com/beyarkay/eskom-calendar/actions/runs/3867863221/jobs/6592931635). Should be fixed in ~15minutes

**Comment by beyarkay** [comment] 2023-01-08 17:08
I can confirm that Tshwane now has loadshedding: 

```
╰→ curl -sL https://github.com/beyarkay/eskom-calendar/releases/download/latest/machine_friendly.csv | rg "tshwane-group-13"
gauteng-tshwane-group-13,2023-01-07T06:00:00+02:00,2023-01-07T08:30:00+02:00,3,"https://twitter.com/Eskom_SA/status/1610958520102305792"
gauteng-tshwane-group-13,2023-01-07T16:00:00+02:00,2023-01-07T16:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1610958520102305792"
gauteng-tshwane-group-13,2023-01-07T22:00:00+02:00,2023-01-08T00:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1610958520102305792"
gauteng-tshwane-group-13,2023-01-08T06:00:00+02:00,2023-01-08T08:30:00+02:00,3,"https://twitter.com/Eskom_SA/status/1612014546377445376"
gauteng-tshwane-group-13,2023-01-08T14:00:00+02:00,2023-01-08T15:59:00+02:00,3,"https://twitter.com/Eskom_SA/status/1612014546377445376"
gauteng-tshwane-group-13,2023-01-08T16:00:00+02:00,2023-01-08T16:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1612014546377445376"
gauteng-tshwane-group-13,2023-01-08T22:00:00+02:00,2023-01-09T00:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1612014546377445376"
gauteng-tshwane-group-13,2023-01-09T04:00:00+02:00,2023-01-09T04:59:00+02:00,4,"https://twitter.com/Eskom_SA/status/1612014546377445376"
gauteng-tshwane-group-13,2023-01-09T05:00:00+02:00,2023-01-09T06:30:00+02:00,3,"https://twitter.com/Eskom_SA/status/1612014546377445376"
gauteng-tshwane-group-13,2023-01-09T12:00:00+02:00,2023-01-09T14:30:00+02:00,3,"https://twitter.com/Eskom_SA/status/1612014546377445376"
gauteng-tshwane-group-13,2023-01-09T20:00:00+02:00,2023-01-09T22:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1612014546377445376"
gauteng-tshwane-group-13,2023-01-10T04:00:00+02:00,2023-01-10T04:59:00+02:00,4,"https://twitter.com/Eskom_SA/status/1612014546377445376"
gauteng-tshwane-group-13,2023-01-10T12:00:00+02:00,2023-01-10T14:30:00+02:00,3,"https://twitter.com/Eskom_SA/status/1612014546377445376"
gauteng-tshwane-group-13,2023-01-10T20:00:00+02:00,2023-01-10T22:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1612014546377445376"
gauteng-tshwane-group-13,2023-01-11T04:00:00+02:00,2023-01-11T04:59:00+02:00,4,"https://twitter.com/Eskom_SA/status/1612014546377445376"
gauteng-tshwane-group-13,2023-01-11T05:00:00+02:00,2023-01-11T06:30:00+02:00,3,"https://twitter.com/Eskom_SA/status/1612014546377445376"
gauteng-tshwane-group-13,2023-01-11T20:00:00+02:00,2023-01-11T22:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1612014546377445376"
gauteng-tshwane-group-13,2023-01-12T04:00:00+02:00,2023-01-12T04:59:00+02:00,4,"https://twitter.com/Eskom_SA/status/1612014546377445376"
```

Feel free to re-open if the issue isn't solved.

**Closed by beyarkay** 2023-01-08 17:08 UTC
