### ISSUE TITLE
Calendar not updated automatically

### ISSUE THREAD

**Issue by itbrl99** [beyarkay/eskom-calendar#411] opened 2023-05-22 10:40 UTC
I have added my link to a new calendar in Outlook. The data is then populated first time but then never gets updated after the first initial ad of the calendar URL.

**Comment by beyarkay** [comment] 2023-05-22 10:57
Can you confirm that you're "subscribing" to the calendar and *not* clicking the link? 

For example, if you wanted to add the Stellenbosch calendar, the URL is https://eskomcalendar.co.za/ec?calendar=western-cape-stellenbosch.ics. Then you need to go to [this outlook webpage](https://outlook.office.com/calendar/addcalendar) and you want to click the "subscribe from web" option:

<img width="1182" alt="Screenshot 2023-05-22 at 12 54 41" src="https://github.com/beyarkay/eskom-calendar/assets/33420535/8140f167-f52d-40d5-a9d3-995997455373">

And then you want to paste the URL https://eskomcalendar.co.za/ec?calendar=western-cape-stellenbosch.ics into the box.

The issue is that if you just click on an ICS URL, by default your calendar app doesn't subscribe to the calendar, but just copies all the data into your calendar.

Let me know if this works!

**Comment by beyarkay** [comment] 2023-05-23 09:05
I'll close this issue on Friday 26 May if there are no further comments

**Closed** 2023-05-29 21:46 UTC
Labels: waiting-on-issuer
